// swift-tools-version:5.9
import PackageDescription

// EkiCore: the app's logic with no Apple-only frameworks (台帳・営業時間・判定器・取込・Places 応答の解釈).
// It builds and tests on Linux (Docker swift:6.0) as well as on macOS/iOS, so the rules in
// コンテンツ設計書 §2・§4・§5 are checked by tests instead of by walking around stations.
// The iOS app (App/, generated by XcodeGen from project.yml) depends on this package.
let package = Package(
    name: "EkiCore",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "EkiCore", targets: ["EkiCore"]),
    ],
    targets: [
        .target(name: "EkiCore", path: "Sources/EkiCore"),
        .testTarget(name: "EkiCoreTests", dependencies: ["EkiCore"], path: "Tests/EkiCoreTests"),
    ],
    swiftLanguageVersions: [.v5]
)
